export const ContestData = [
    {
        id: 0,
        img: "https://images.pexels.com/photos/97587/pexels-photo-97587.jpeg?auto=compress&cs=tinysrgb&w=1600",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    {
        id: 1,
        img: "https://images.pexels.com/photos/203555/pexels-photo-203555.jpeg?auto=compress&cs=tinysrgb&w=1600",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    
    {
        id: 2,
        img: "https://images.pexels.com/photos/2403611/pexels-photo-2403611.jpeg?auto=compress&cs=tinysrgb&w=1600",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    {
        id: 3,
        img: "https://images.pexels.com/photos/7551385/pexels-photo-7551385.jpeg?auto=compress&cs=tinysrgb&w=1600",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    {
        id: 4,
        img: "https://images.pexels.com/photos/139392/checkmate-chess-resignation-conflict-139392.jpeg?auto=compress&cs=tinysrgb&w=1600",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    {
        id: 5,
        img: "https://images.pexels.com/photos/139392/checkmate-chess-resignation-conflict-139392.jpeg?auto=compress&cs=tinysrgb&w=1600",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    
    {
        id: 6,
        img: "https://images.pexels.com/photos/139392/checkmate-chess-resignation-conflict-139392.jpeg?auto=compress&cs=tinysrgb&w=1600",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    {
        id: 7,
        img: "https://images.pexels.com/photos/1552617/pexels-photo-1552617.jpeg?auto=compress&cs=tinysrgb&w=1600",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    
]

