export const EventData = [
    {
        id: 0,
        img: "https://images.pexels.com/photos/787961/pexels-photo-787961.jpeg?auto=compress&cs=tinysrgb&w=1600",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    {
        id: 1,
        img: "https://images.pexels.com/photos/2306281/pexels-photo-2306281.jpeg?auto=compress&cs=tinysrgb&w=1600",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    
    {
        id: 2,
        img: "https://images.pexels.com/photos/2608517/pexels-photo-2608517.jpeg?auto=compress&cs=tinysrgb&w=1600",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    {
        id: 3,
        img: "https://images.pexels.com/photos/2263436/pexels-photo-2263436.jpeg?auto=compress&cs=tinysrgb&w=1600",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    {
        id: 4,
        img: "https://images.pexels.com/photos/587741/pexels-photo-587741.jpeg?auto=compress&cs=tinysrgb&w=1600",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    {
        id: 5,
        img: "https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1600",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    
    {
        id: 6,
        img: "https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg?auto=compress&cs=tinysrgb&w=1600",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    {
        id: 7,
        img: "https://images.pexels.com/photos/50675/banquet-wedding-society-deco-50675.jpeg?auto=compress&cs=tinysrgb&w=1600",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    
]

