export const FormData = [
    {
        id: 0,
        img: "https://images.pexels.com/photos/12897542/pexels-photo-12897542.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    {
        id: 1,
        img: "https://images.pexels.com/photos/18968224/pexels-photo-18968224/free-photo-of-light.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    
    {
        id: 2,
        img: "https://images.pexels.com/photos/18928507/pexels-photo-18928507/free-photo-of-fireworks-in-the-dark-sky-with-a-black-background.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    {
        id: 3,
        img: "https://images.pexels.com/photos/8486108/pexels-photo-8486108.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    {
        id: 4,
        img: "https://images.pexels.com/photos/12897542/pexels-photo-12897542.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    {
        id: 5,
        img: "https://images.pexels.com/photos/18968224/pexels-photo-18968224/free-photo-of-light.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    
    {
        id: 6,
        img: "https://images.pexels.com/photos/18928507/pexels-photo-18928507/free-photo-of-fireworks-in-the-dark-sky-with-a-black-background.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    {
        id: 7,
        img: "https://images.pexels.com/photos/8486108/pexels-photo-8486108.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
        title: "Laff Matters 10.0",
        location: "Location: Portharcut",
        description1: "February 25, 2023",
        description2: "from",
        button: " Get Ticket",
        price: "5,000.00",
    },
    
]

